---
version: 2.1

orbs:
    codecov: codecov/codecov@1.1.3

jobs:
    build_and_test:
        docker:
            - image: cimg/python:3.8.0
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - deps-{{ checksum "poetry.lock" }}
            - run:
                  name: Install Dependencies
                  command: poetry install
            - save_cache:
                  key: deps-{{ checksum "poetry.lock" }}
                  paths:
                      - /home/circleci/.cache/pypoetry/virtualenvs
            - run:
                  name: Run pylint
                  command: poetry run pylint src/ tests/
            - run:
                  name: Run black
                  command: poetry run black --check .
            - run:
                  name: Run isort
                  command: poetry run isort .
            - run:
                  name: Run Tests
                  command: poetry run pytest -vv --cov=src --cov-fail-under=70 --cov-report=term --cov-report=xml
            - codecov/upload:
                  file: coverage.xml

    docker_build:
        machine: true
        steps:
            - checkout
            - run:
                  name: Docker Build and Run
                  command: |
                      docker build . -t google-photos-archiver:$CIRCLE_BRANCH
                      docker run google-photos-archiver:$CIRCLE_BRANCH

    gh_release:
        docker:
            - image: cimg/python:3.8.0
        steps:
            - checkout
            - run: pip install python-semantic-release
            - run: git config --global user.email "scottx611x@gmail.com"
            - run: git config --global user.name "Scott Ouellette"
            - run: semantic-release version
            - run: git push origin --tags

    pypi_publish:
        docker:
            - image: cimg/python:3.8.0
        steps:
            - checkout
            - run:
                  name: Push to PyPI
                  command: |
                      pip install poetry-dynamic-versioning
                      poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

workflows:
    build_and_test:
        jobs:
            - build_and_test
            - docker_build
            - gh_release:
                  filters:
                      branches:
                          only: main
                  requires:
                      - build_and_test
                      - docker_build

    publish:
        jobs:
            - build_and_test:
                  filters:
                      tags:
                          only: /v[0-9]+(\.[0-9]+)*/
                      branches:
                          ignore: /.*/
            - docker_build:
                  filters:
                      tags:
                          only: /v[0-9]+(\.[0-9]+)*/
                      branches:
                          ignore: /.*/
            - pypi_publish:
                  requires:
                      - build_and_test
                      - docker_build
                  filters:
                      tags:
                          only: /v[0-9]+(\.[0-9]+)*/
                      branches:
                          ignore: /.*/
